### ISSUE TITLE
Hyperlink removal in Navigationbar

### ISSUE THREAD

**Issue by Julius-crt** [AryehSchoefer/SkSy-Hausaufgabe-1#4]
Hey Aryeh, die Beispiel Navigationsbar in index.html, hat einen Hyperlink ins Parentdirectory. Ist das nicht ein Sicherheitsproblem?
lg

**Comment by AryehSchoefer** [comment]
Heyho, das ist tatsächlich in diesem Fall nicht gefährlich, weil wir keine protected routes benutzen (/admin oder so). Hätte man so protected routes, würde man diese auch mit extra code blockieren, damit wenn der user nicht ausreichende Berechtigung besitzt, dieser die Seite nicht sehen kann. Allgemein kannst du die Parentdirectory auf vielen Seiten sehen (Inspect Element auf die Seite und dann oben auf Sources).
