### ISSUE TITLE
Add smartphone Design

### ISSUE THREAD

**Issue by Julius-crt** [AryehSchoefer/SkSy-Hausaufgabe-1#7]
Hey, als Desktop webbrowser Seite sieht alles ganz gut aus, allerdings ist die add/edit Seite auf dem Smartphone nicht schön anzusehen

**Comment by AryehSchoefer** [comment]
Ich kümmer mich drum

**Comment by Julius-crt** [comment]
ist mega geworden :) Danke das du das übernommen hast, ich wollte eigentlich nur mal mein erste eigenes Issue aufmachen
